// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA19PegVUoz0QcTSc4mUO5yBa-y2H6_V4E',
    appId: '1:919624766968:web:000378e089b29af8d9320d',
    messagingSenderId: '919624766968',
    projectId: 'dpia-lite',
    authDomain: 'dpia-lite.firebaseapp.com',
    storageBucket: 'dpia-lite.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVrnCgATaKKUnte6EGlJAHoOv0flZ75us',
    appId: '1:919624766968:android:4cd0795279a6de80d9320d',
    messagingSenderId: '919624766968',
    projectId: 'dpia-lite',
    storageBucket: 'dpia-lite.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtnJu90f4guxj0lY9Szz8RDbJid-_h8DI',
    appId: '1:919624766968:ios:bead615430022373d9320d',
    messagingSenderId: '919624766968',
    projectId: 'dpia-lite',
    storageBucket: 'dpia-lite.appspot.com',
    iosBundleId: 'com.example.dpiaProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtnJu90f4guxj0lY9Szz8RDbJid-_h8DI',
    appId: '1:919624766968:ios:72265640509b2254d9320d',
    messagingSenderId: '919624766968',
    projectId: 'dpia-lite',
    storageBucket: 'dpia-lite.appspot.com',
    iosBundleId: 'com.example.dpiaProject.RunnerTests',
  );
}
